# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180411_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(max_length=150, upload_to=b''),
        ),
    ]
